import joblib
import numpy as np
import pandas as pd
from flask import Flask, render_template, request

app = Flask(__name__)

model = joblib.load('models/randomforest_model.pkl')  # loading the saved random forest classifier model.


@app.route('/')
def home():
    return render_template('index.html')


@app.route('/predict', methods=['GET', 'POST'])
def predict():
    """
    For rendering results on HTML GUI

    """
    if request.method == "POST":
        # ['category', 'amt', 'zip', 'city_pop', 'job', 'cust_age_groups','trans_hour', 'gender_M']

        f_list = [request.form.get('merch_catg'), request.form.get('txn_amt'), request.form.get('zp_cd'),
                  request.form.get('city_pop'), request.form.get('job'), request.form.get('Customer age group'),
                  request.form.get('txn_time'), request.form.get('gender')]  # list of inputs

        final_features = np.array(f_list).reshape(-1, 8)

        df = pd.DataFrame(final_features,
                          columns=['category', 'amt', 'zip', 'city_pop', 'job', 'cust_age_groups', 'trans_hour',
                                   'gender_M'])
        # transforming the columns
        df['category'] = df['category'].map({'Travel': 0,
                                             'Grocery-Online': 1,
                                             'Gas-Transport': 2,
                                             'Kids-Pets': 3,
                                             'Health & Fitness': 4,
                                             'Personal care': 5,
                                             'Food & Dining': 6,
                                             'Miscellaneous-POS': 7,
                                             'Home': 8,
                                             'Grocery-POS': 9,
                                             'Entertainment': 10,
                                             'Miscellaneous-Online': 11,
                                             'Shopping-POS': 12,
                                             'Shopping-Online': 13})
        df['job'] = df['job'].map({'Stage manager': 0,
                                   'Engineer, communications': 1,
                                   'Engineer, drilling': 2,
                                   'Theatre manager': 3,
                                   'Geophysicist/field seismologist': 4,
                                   'Information officer': 5,
                                   'Pathologist': 6,
                                   'Designer, furniture': 7,
                                   'Statistician': 8,
                                   'Contractor': 9,
                                   'English as a foreign language teacher': 10,
                                   'Retail banker': 11,
                                   'Merchandiser, retail': 12,
                                   'Chartered legal executive (England and Wales)': 13,
                                   'Teacher, English as a foreign language': 14,
                                   'Designer, exhibition/display': 15,
                                   'Logistics and distribution manager': 16,
                                   'Planning and development surveyor': 17,
                                   'Dispensing optician': 18,
                                   'Training and development officer': 19,
                                   'Investment banker, operational': 20,
                                   'Public house manager': 21,
                                   'Research scientist (life sciences)': 22,
                                   'Pension scheme manager': 23,
                                   'Water engineer': 24,
                                   'Surveyor, rural practice': 25,
                                   'Geneticist, molecular': 26,
                                   'Hydrogeologist': 27,
                                   'Phytotherapist': 28,
                                   'Insurance underwriter': 29,
                                   'Arboriculturist': 30,
                                   'Research officer, trade union': 31,
                                   'Airline pilot': 32,
                                   'Scientist, research (physical sciences)': 33,
                                   'Herpetologist': 34,
                                   'Mudlogger': 35,
                                   'Chief Executive Officer': 36,
                                   'Orthoptist': 37,
                                   'Ecologist': 38,
                                   'Leisure centre manager': 39,
                                   'Animal technologist': 40,
                                   'Travel agency manager': 41,
                                   'Sports development officer': 42,
                                   'Product/process development scientist': 43,
                                   'Manufacturing systems engineer': 44,
                                   'Sports administrator': 45,
                                   'Writer': 46,
                                   'Counsellor': 47,
                                   'Special educational needs teacher': 48,
                                   'Analytical chemist': 49,
                                   'Scientist, audiological': 50,
                                   'Conservator, museum/gallery': 51,
                                   'Public librarian': 52,
                                   'Records manager': 53,
                                   'Scientist, clinical (histocompatibility and immunogenetics)': 54,
                                   'Interpreter': 55,
                                   'Retail manager': 56,
                                   'Engineer, manufacturing': 57,
                                   'Electrical engineer': 58,
                                   'Neurosurgeon': 59,
                                   'Museum/gallery exhibitions officer': 60,
                                   'Buyer, retail': 61,
                                   'Environmental consultant': 62,
                                   'Armed forces technical officer': 63,
                                   'Clinical research associate': 64,
                                   'Higher education careers adviser': 65,
                                   'Industrial/product designer': 66,
                                   'Nature conservation officer': 67,
                                   'Arts development officer': 68,
                                   'Oncologist': 69,
                                   'Archaeologist': 70,
                                   'Community development worker': 71,
                                   'Primary school teacher': 72,
                                   'Pharmacologist': 73,
                                   'Multimedia programmer': 74,
                                   'Civil Service administrator': 75,
                                   'Investment analyst': 76,
                                   'Psychotherapist': 77,
                                   'IT trainer': 78,
                                   'Editor, commissioning': 79,
                                   'Sub': 80,
                                   'Osteopath': 81,
                                   'Cabin crew': 82,
                                   'Clinical biochemist': 83,
                                   'Risk analyst': 84,
                                   'Seismic interpreter': 85,
                                   'Air broker': 86,
                                   'Paramedic': 87,
                                   'Civil Service fast streamer': 88,
                                   'English as a second language teacher': 89,
                                   'Corporate investment banker': 90,
                                   'Education officer, community': 91,
                                   'Therapist, sports': 92,
                                   'Financial trader': 93,
                                   'Amenity horticulturist': 94,
                                   'Health physicist': 95,
                                   'Administrator, charities/voluntary organisations': 96,
                                   'Energy engineer': 97,
                                   'Communications engineer': 98,
                                   'Legal secretary': 99,
                                   'Textile designer': 100,
                                   'Location manager': 101,
                                   'Furniture conservator/restorer': 102,
                                   'Buyer, industrial': 103,
                                   'Producer, radio': 104,
                                   'Toxicologist': 105,
                                   'Psychologist, sport and exercise': 106,
                                   'Video editor': 107,
                                   'Drilling engineer': 108,
                                   'Early years teacher': 109,
                                   'Television floor manager': 110,
                                   'Clinical cytogeneticist': 111,
                                   'Colour technologist': 112,
                                   'Race relations officer': 113,
                                   'Sales professional, IT': 114,
                                   'Immunologist': 115,
                                   'Warden/ranger': 116,
                                   'Engineer, mining': 117,
                                   'Psychologist, counselling': 118,
                                   'Aeronautical engineer': 119,
                                   'Land/geomatics surveyor': 120,
                                   'Programme researcher, broadcasting/film/video': 121,
                                   'Therapist, drama': 122,
                                   'Museum education officer': 123,
                                   'Magazine features editor': 124,
                                   'Paediatric nurse': 125,
                                   'Music therapist': 126,
                                   'Prison officer': 127,
                                   'Site engineer': 128,
                                   'Engineer, maintenance': 129,
                                   'Solicitor': 130,
                                   'Learning mentor': 131,
                                   'Therapist, music': 132,
                                   'Ambulance person': 133,
                                   'Scientist, research (medical)': 134,
                                   'Farm manager': 135,
                                   'Secretary/administrator': 136,
                                   'Copywriter, advertising': 137,
                                   'Engineer, water': 138,
                                   'Museum/gallery conservator': 139,
                                   'Technical brewer': 140,
                                   'Teacher, secondary school': 141,
                                   'Therapist, horticultural': 142,
                                   'Learning disability nurse': 143,
                                   'Insurance broker': 144,
                                   'Science writer': 145,
                                   'Engineer, broadcasting (operations)': 146,
                                   'Teacher, early years/pre': 147,
                                   'Engineer, structural': 148,
                                   'Clothing/textile technologist': 149,
                                   'Radiographer, diagnostic': 150,
                                   'Musician': 151,
                                   'Wellsite geologist': 152,
                                   'Doctor, hospital': 153,
                                   'Copy': 154,
                                   'Diagnostic radiographer': 155,
                                   'Petroleum engineer': 156,
                                   'Information systems manager': 157,
                                   'Press sub': 158,
                                   'Hotel manager': 159,
                                   'Animal nutritionist': 160,
                                   'Occupational hygienist': 161,
                                   'Professor Emeritus': 162,
                                   'Podiatrist': 163,
                                   'Trading standards officer': 164,
                                   'Media planner': 165,
                                   'Radio producer': 166,
                                   'Building control surveyor': 167,
                                   'Manufacturing engineer': 168,
                                   'Interior and spatial designer': 169,
                                   'Product designer': 170,
                                   'Camera operator': 171,
                                   'Forensic psychologist': 172,
                                   'Accountant, chartered': 173,
                                   'Chemist, analytical': 174,
                                   'Aid worker': 175,
                                   'IT consultant': 176,
                                   'Psychologist, clinical': 177,
                                   'Barrister': 178,
                                   'Psychiatric nurse': 179,
                                   'Conservator, furniture': 180,
                                   'Chief Strategy Officer': 181,
                                   'Restaurant manager, fast food': 182,
                                   'Development worker, community': 183,
                                   'Ceramics designer': 184,
                                   'Engineer, building services': 185,
                                   'Theatre director': 186,
                                   'Tourist information centre manager': 187,
                                   'Conservation officer, historic buildings': 188,
                                   'Theme park manager': 189,
                                   'Horticultural consultant': 190,
                                   'Purchasing manager': 191,
                                   'Teacher, adult education': 192,
                                   'Surveyor, mining': 193,
                                   "Barrister's clerk": 194,
                                   'Music tutor': 195,
                                   'Futures trader': 196,
                                   'Media buyer': 197,
                                   'Curator': 198,
                                   'Forest/woodland manager': 199,
                                   'Applications developer': 200,
                                   'Designer, ceramics/pottery': 201,
                                   'Architectural technologist': 202,
                                   'Private music teacher': 203,
                                   'Engineer, civil (consulting)': 204,
                                   'Set designer': 205,
                                   'Embryologist, clinical': 206,
                                   'Surveyor, land/geomatics': 207,
                                   'Press photographer': 208,
                                   'Designer, textile': 209,
                                   'Medical technical officer': 210,
                                   'Engineer, control and instrumentation': 211,
                                   'Teaching laboratory technician': 212,
                                   'Tourism officer': 213,
                                   'Marketing executive': 214,
                                   'Insurance risk surveyor': 215,
                                   'Animator': 216,
                                   'Librarian, public': 217,
                                   'Commercial/residential surveyor': 218,
                                   'Engineering geologist': 219,
                                   'Horticultural therapist': 220,
                                   'Development worker, international aid': 221,
                                   'Regulatory affairs officer': 222,
                                   'Broadcast engineer': 223,
                                   'Engineer, automotive': 224,
                                   'Psychiatrist': 225,
                                   'Chief Marketing Officer': 226,
                                   'Fisheries officer': 227,
                                   'Accountant, chartered public finance': 228,
                                   'Radiographer, therapeutic': 229,
                                   'Tax inspector': 230,
                                   'Pensions consultant': 231,
                                   'Research scientist (maths)': 232,
                                   'Scientist, biomedical': 233,
                                   'Exhibition designer': 234,
                                   'Electronics engineer': 235,
                                   'Occupational psychologist': 236,
                                   'Counselling psychologist': 237,
                                   'Lawyer': 238,
                                   'Psychotherapist, child': 239,
                                   'Community arts worker': 240,
                                   'Trade mark attorney': 241,
                                   'Exhibitions officer, museum/gallery': 242,
                                   'Economist': 243,
                                   'Engineer, production': 244,
                                   'Claims inspector/assessor': 245,
                                   'Facilities manager': 246,
                                   'Surveyor, minerals': 247,
                                   'Film/video editor': 248,
                                   'Special effects artist': 249,
                                   'Production manager': 250,
                                   'Research scientist (physical sciences)': 251,
                                   'Mechanical engineer': 252,
                                   'Visual merchandiser': 253,
                                   'Tour manager': 254,
                                   'Designer, multimedia': 255,
                                   'Intelligence analyst': 256,
                                   'Dealer': 257,
                                   'Engineer, biomedical': 258,
                                   'Make': 259,
                                   'Engineer, petroleum': 260,
                                   'Medical secretary': 261,
                                   'Environmental education officer': 262,
                                   'Administrator, arts': 263,
                                   'Production assistant, radio': 264,
                                   'Designer, industrial/product': 265,
                                   'Comptroller': 266,
                                   'Chartered loss adjuster': 267,
                                   'Retail merchandiser': 268,
                                   'Retail buyer': 269,
                                   'Product manager': 270,
                                   'Data scientist': 271,
                                   'Biomedical scientist': 272,
                                   'Exercise physiologist': 273,
                                   'Warehouse manager': 274,
                                   'Maintenance engineer': 275,
                                   'Community pharmacist': 276,
                                   'Nutritional therapist': 277,
                                   'Scientist, marine': 278,
                                   'Administrator, education': 279,
                                   'Optician, dispensing': 280,
                                   'Broadcast journalist': 281,
                                   'Lexicographer': 282,
                                   'Insurance claims handler': 283,
                                   'Event organiser': 284,
                                   'Glass blower/designer': 285,
                                   'Research officer, political party': 286,
                                   'Pilot, airline': 287,
                                   'Commercial horticulturist': 288,
                                   'Health and safety adviser': 289,
                                   'Advertising account planner': 290,
                                   'Archivist': 291,
                                   'Physiotherapist': 292,
                                   'Financial adviser': 293,
                                   'Engineer, agricultural': 294,
                                   'Armed forces logistics/support/administrative officer': 295,
                                   'Dance movement psychotherapist': 296,
                                   'Geologist, engineering': 297,
                                   'Nurse, mental health': 298,
                                   'Charity fundraiser': 299,
                                   'Materials engineer': 300,
                                   'Scientist, research (maths)': 301,
                                   'Lecturer, higher education': 302,
                                   'Patent attorney': 303,
                                   'Field trials officer': 304,
                                   'Editor, magazine features': 305,
                                   'Librarian, academic': 306,
                                   'Armed forces training and education officer': 307,
                                   'Engineer, materials': 308,
                                   'Fine artist': 309,
                                   'Television camera operator': 310,
                                   'Production engineer': 311,
                                   'Advice worker': 312,
                                   'Air cabin crew': 313,
                                   'Mental health nurse': 314,
                                   'Senior tax professional/tax inspector': 315,
                                   'Environmental manager': 316,
                                   'Psychologist, forensic': 317,
                                   'Broadcast presenter': 318,
                                   'Jewellery designer': 319,
                                   'Optometrist': 320,
                                   'Journalist, newspaper': 321,
                                   'Secondary school teacher': 322,
                                   'Control and instrumentation engineer': 323,
                                   'Engineer, land': 324,
                                   'Fitness centre manager': 325,
                                   'Network engineer': 326,
                                   'Education officer, museum': 327,
                                   'General practice doctor': 328,
                                   'Environmental health practitioner': 329,
                                   'Licensed conveyancer': 330,
                                   "Politician's assistant": 331,
                                   'Television/film/video producer': 332,
                                   'Therapist, occupational': 333,
                                   'Chiropodist': 334,
                                   'Charity officer': 335,
                                   'Tree surgeon': 336,
                                   'Social researcher': 337,
                                   'Civil engineer, contracting': 338,
                                   'Editor, film/video': 339,
                                   'Educational psychologist': 340,
                                   'Child psychotherapist': 341,
                                   'Metallurgist': 342,
                                   'Surgeon': 343,
                                   'Personnel officer': 344,
                                   'Radio broadcast assistant': 345,
                                   'Doctor, general practice': 346,
                                   'Human resources officer': 347,
                                   'Firefighter': 348,
                                   'Herbalist': 349,
                                   'Public affairs consultant': 350,
                                   'Scientist, physiological': 351,
                                   'Public relations account executive': 352,
                                   'Presenter, broadcasting': 353,
                                   'Probation officer': 354,
                                   "Nurse, children's": 355,
                                   'Further education lecturer': 356,
                                   'Cytogeneticist': 357,
                                   'Systems developer': 358,
                                   'Geoscientist': 359,
                                   'Health service manager': 360,
                                   'Chartered public finance accountant': 361,
                                   'Historic buildings inspector/conservation officer': 362,
                                   'Programmer, applications': 363,
                                   'Operations geologist': 364,
                                   'Furniture designer': 365,
                                   'Veterinary surgeon': 366,
                                   'Education administrator': 367,
                                   'Tax adviser': 368,
                                   'Accounting technician': 369,
                                   'Estate manager/land agent': 370,
                                   'Physicist, medical': 371,
                                   'Systems analyst': 372,
                                   'Energy manager': 373,
                                   'Geochemist': 374,
                                   'Emergency planning/management officer': 375,
                                   'Television production assistant': 376,
                                   'Quantity surveyor': 377,
                                   'Chief Technology Officer': 378,
                                   'Call centre manager': 379,
                                   'Scientific laboratory technician': 380,
                                   'Freight forwarder': 381,
                                   'Heritage manager': 382,
                                   'Administrator': 383,
                                   'Garment/textile technologist': 384,
                                   'Loss adjuster, chartered': 385,
                                   'Waste management officer': 386,
                                   'Oceanographer': 387,
                                   'Administrator, local government': 388,
                                   'TEFL teacher': 389,
                                   'Landscape architect': 390,
                                   'Teacher, special educational needs': 391,
                                   'Volunteer coordinator': 392,
                                   'Careers adviser': 393,
                                   'Cartographer': 394,
                                   'Solicitor, Scotland': 395,
                                   'Database administrator': 396,
                                   'Engineer, electronics': 397,
                                   'Artist': 398,
                                   'Building surveyor': 399,
                                   'Mining engineer': 400,
                                   'Web designer': 401,
                                   'Academic librarian': 402,
                                   'Designer, television/film set': 403,
                                   'Advertising copywriter': 404,
                                   'Equities trader': 405,
                                   'Investment banker, corporate': 406,
                                   'Police officer': 407,
                                   'Designer, interior/spatial': 408,
                                   'Homeopath': 409,
                                   'Chemical engineer': 410,
                                   'Associate Professor': 411,
                                   'Market researcher': 412,
                                   'Hospital doctor': 413,
                                   'Dancer': 414,
                                   'Production assistant, television': 415,
                                   'Chief Operating Officer': 416,
                                   'Naval architect': 417,
                                   'Occupational therapist': 418,
                                   'Advertising account executive': 419,
                                   'Programmer, multimedia': 420,
                                   'Biomedical engineer': 421,
                                   'Town planner': 422,
                                   'Outdoor activities/education manager': 423,
                                   'Physiological scientist': 424,
                                   'Operational researcher': 425,
                                   'Audiological scientist': 426,
                                   'Bookseller': 427,
                                   'Pharmacist, community': 428,
                                   'Geologist, wellsite': 429,
                                   'Chartered accountant': 430,
                                   'Accountant, chartered certified': 431,
                                   'Acupuncturist': 432,
                                   'Illustrator': 433,
                                   'Chief of Staff': 434,
                                   'Transport planner': 435,
                                   'Art therapist': 436,
                                   'Magazine journalist': 437,
                                   'Barista': 438,
                                   'Designer, jewellery': 439,
                                   'Chief Financial Officer': 440,
                                   'Producer, television/film/video': 441,
                                   'Industrial buyer': 442,
                                   'Agricultural consultant': 443,
                                   'Immigration officer': 444,
                                   'Soil scientist': 445,
                                   'Lecturer, further education': 446,
                                   'Water quality scientist': 447,
                                   'Research scientist (medical)': 448,
                                   'Pharmacist, hospital': 449,
                                   'Management consultant': 450,
                                   'Sales promotion account executive': 451,
                                   'Telecommunications researcher': 452,
                                   'Therapist, art': 453,
                                   'Quarry manager': 454,
                                   'Company secretary': 455,
                                   'Biochemist, clinical': 456,
                                   'Rural practice surveyor': 457,
                                   'Health visitor': 458,
                                   'Contracting civil engineer': 459,
                                   'Horticulturist, commercial': 460,
                                   'Surveyor, hydrographic': 461,
                                   'Equality and diversity officer': 462,
                                   'Land': 463,
                                   'Sport and exercise psychologist': 464,
                                   'Engineer, technical sales': 465,
                                   'Social research officer, government': 466,
                                   'Gaffer': 467,
                                   'Air traffic controller': 468,
                                   'Structural engineer': 469,
                                   'Software engineer': 470,
                                   'Architect': 471,
                                   'Field seismologist': 472,
                                   'Teacher, primary school': 473,
                                   'Engineer, site': 474,
                                   'Operational investment banker': 475,
                                   'Building services engineer': 476,
                                   'Minerals surveyor': 477,
                                   'Medical sales representative': 478,
                                   'Engineer, civil (contracting)': 479,
                                   'Sales executive': 480,
                                   'Careers information officer': 481,
                                   'Hydrographic surveyor': 482,
                                   'Local government officer': 483,
                                   'Engineer, aeronautical': 484,
                                   'Art gallery manager': 485,
                                   'Public relations officer': 486,
                                   'Catering manager': 487,
                                   'Plant breeder/geneticist': 488,
                                   'Hospital pharmacist': 489,
                                   'Medical physicist': 490,
                                   'Commissioning editor': 491,
                                   'Hydrologist': 492,
                                   'Clinical psychologist': 493,
                                   'Community education officer': 494,
                                   'Ship broker': 495,
                                   'Health promotion specialist': 496})
        # ['category', 'amt', 'zip', 'city_pop', 'job', 'cust_age_groups','trans_hour', 'gender_M']

        df['cust_age_groups'] = df['cust_age_groups'].map({'40-50': 0,
                                                           '30-40': 1,
                                                           '20-30': 2,
                                                           'Above 80': 3,
                                                           '50-60': 4,
                                                           '10-20': 5,
                                                           '60-70': 6,
                                                           '70-80': 7})

        df['trans_hour'] = df['trans_hour'].astype('int')

        df['gender_M'] = df['gender_M'].map({'Male': 1, 'Female': 0})

        df['amt'] = df['amt'].astype('float')
        df['amt'] = df['amt'].apply(lambda x: np.log(x + 1))

        df['city_pop'] = df['city_pop'].astype('int')
        df['city_pop'] = df['city_pop'].apply(lambda x: np.log(x + 1))

        df['zip'] = df['zip'].astype('int')

        print(df)
        prediction = model.predict(df)
        result_dict = {0: 'Non-fraudulent', 1: 'Fraudulent'}
        result = result_dict.get(prediction[0])

        return render_template('index.html',
                               prediction_text=f"This transaction is {result}")


if __name__ == "__main__":
    app.run(debug=True)
